title: Radio Cempaka Angkasa 102.1 FM
description: "102.1 RCA FM AsooOy - Radio lokal berpuluh puluh tahun dengan acara variatifnya dan sudah terkenal dengan segitiga RCA nya"
baseurl: ""
url: "https://rcafm.asooy.web.id"

author:
  name: "ganis"
  email: "rcafmkotabanjar@gmail.com"

favicon: "/assets/image/favicon-32x32.png"

collections:
  news:
    output: true
    permalink: /posts/{title}/
