backend:
  name: github
  repo: rafi-sudo/webradio-leathertheme
  branch: main
  auth_scope: repo
  client_id: "Ov23limR6Dv4EKq2ZYxP"

media_folder: "assets/image"
public_folder: "/assets/image"

collections:
  - name: "pages"
    label: "Halaman Website"
    files:
      - label: "Tentang Kami"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }

      - label: "Event Off Air"
        name: "gallery"
        file: "gallery.md"
        fields:
          - { label: "Judul Program", name: "title", widget: "string" }
          - { label: "Isi Program", name: "body", widget: "markdown" }
          
      - label: "Pedoman Media Siber"
        name: "pedoman-media-siber"
        file: "pedoman-media-siber.md"
        fields:
          - { label: "Judul Program", name: "title", widget: "string" }
          - { label: "Isi Program", name: "body", widget: "markdown" }

      - label: "Program Unggulan Section 1"
        name: "program"
        file: "program.md"
        fields:
          - { label: "Judul Program", name: "title", widget: "string" }
          - { label: "Isi Program", name: "body", widget: "markdown" }

      - label: "Program Unggulan Section 2"
        name: "program1"
        file: "program1.md"
        fields:
          - { label: "Judul Program", name: "title", widget: "string" }
          - { label: "Isi Program", name: "body", widget: "markdown" }

      - label: "Program Unggulan Section 3"
        name: "program2"
        file: "program2.md"
        fields:
          - { label: "Judul Program", name: "title", widget: "string" }
          - { label: "Isi Program", name: "body", widget: "markdown" }

      - label: "Program Unggulan Section 4"
        name: "program3"
        file: "program3.md"
        fields:
          - { label: "Judul Program", name: "title", widget: "string" }
          - { label: "Isi Program", name: "body", widget: "markdown" }

      - label: "Program Unggulan Section 5"
        name: "program4"
        file: "program4.md"
        fields:
          - { label: "Judul Program", name: "title", widget: "string" }
          - { label: "Isi Program", name: "body", widget: "markdown" }
