backend:
  name: github
  repo: username/nama-repo
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Halaman Website"
    files:
      - label: "Tentang Kami"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Halaman", name: "body", widget: "markdown" }

      - label: "Program 1"
        name: "program1"
        file: "program1.md"
        fields:
          - { label: "Judul Program", name: "title", widget: "string" }
          - { label: "Isi Program", name: "body", widget: "markdown" }

      - label: "Kontak"
        name: "kontak"
        file: "kontak.md"
        fields:
          - { label: "Judul", name: "title", widget: "string" }
          - { label: "Isi Kontak", name: "body", widget: "markdown" }
